---
title: "Make progress on projects"
output: 
  tufte::tufte_html:
    css: ../lab.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(vembedr)
```

This week you'll be working on your projects.
This means no separate `lab-08` repo for your lab, everything goes in your project repo.
And we won't be scoring this lab, so no deadline next Tuesday either. 
At this point your focus should be on finishing up your projects!

# Logistics

1. **Review evaluation criteria:** When evaluating your project, we will consider the following questions:

- Content: Is the research question well designed and is the data being used relevant to the research question?
- Content: Did the team use appropriate statistical procedures and interpretations of results accurately?
- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered?
- Does it appear that time and effort went into the planning and implementation of the project?
- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
- Professionalism: How well did the team present? Does the presentation appear to be well practised? Did everyone get a chance to say something meaningful about the project?
- Teamwork: Did the team present a unified story, or did it seem like independent pieces of work patched together?
- Time management: Did the team divide the time well amongst themselves or got cut off going over time?
- Executive summary: Does it follow guidance? Is it concise but detailed enough?

2. **Discuss making your project repo public:** If everyone on the team agrees, after the semester ends, I can clean your repo of any issues including marks and then make it public and transfer ownership to you (once grades for the course have been officially posted). This is a souvenir from IDS to you and something you can add to your data science portfolio! This is entirely optional and your score on the project will in no way be impacted by your decision. Let me know your decision sometime before the course ends!

# Project progress

Now back to your project...

3. **Craft your to-do list:** Discuss your plan for your project as a team, review existing issues and open new ones as needed. Not every issue needs to have a checklist, but you might want to include checklists in some of them to remind yourselves the exact steps you discussed to tackle the issue. Then assign **at least one** issue to each team member. 

4. **Cite your data:** Now is the time to fix up those citations! In your project README there is a link to a resource for properly citing data. Develop a citation for your dataset and add it under the data section using this guidance. If you have questions, ask a tutor for help!

5. **Strongly recommended:** Get a hold of a tutor and run your ideas by them. Give them a 30 second version of your 5 minute presentation and ask for their feedback.
