---
title: "Lab 07 - Work on projects"
output: 
  tufte::tufte_html:
    css: ../lab.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This week you'll be working on your projects.
This means no separate `lab-07` repo for your lab, everything goes in your project repo.
Your lab score will be based on having completed these steps and, as usual, individual contributions to the project repo for these particular tasks.

Once you complete these, use the rest of the time to, well, work on your project!
Remember, your project assignment is [here](https://idsed.digital/assessments/project/).

If you haven't yet done so go to the course organization on GitHub and clone your project repo titled `project-TEAM_NAME`.

## Extra

You may notice a folder called `extra` in your repos.
Any extra documents you might have go here.
This might include Rmd files you're using to develop your project, any notes, or anything else.
The contents of this folder will **not** be marked, it's just a convenient place to store documents and collaborate with teammates without cluttering the rest of your repo.

-   If you have any extra documents in your repo, move them into this folder. To move files in RStudio: go to your Files pane and check the boxes next to the files you want to move, click on More, and then Move... and select the `extra` folder.
- Now is also a good time to generally check things are in the right place (e.g. data is only in the data folder).
-   Commit and push your changes.

```{marginfigure}
On the repository on GitHub, you probably want to click on the gear icon next to **About** and add a very brief description of your project.
```

## README

Add your project title and team name to the `README.Rmd` file in the repo.
Knit, commit, and push your changes to `README.Rmd` and `README.md`.
Observe that these are updated in the README of the repo.

## Presentation

-   Open the `presentation.Rmd` file in one of the subfolders in the `presentation` folder, knit the document, and review the presentation format. Now try the other template. Once you have made a decision about which html slide library to use, move or copy all the contents of the chosen template into the main `presentation` folder. Update the YAML with your project title, team name, etc. and commit and push your changes.

```{marginfigure}
Remember that your data lives in a folder called data that is not inside your presentation folder. So you need to specify the path to your data with here::here("data/name_of_datafile") in your read_csv() (or similar) function.
```

- Load your data in your `presentation.Rmd`, knit, and make sure everything works. Commit and push your updated proposal to your project repo.

- To view the slides/present them, you can make sure the knitted file opens in a "viewer pane", making sure the settings under the gear icon (next to "Knit"), are set to "preview in viewer pane".

## Planning

Now that all the logistical details are done, start work on the planning of your project.

-   Discuss how, if at all, you might incorporate modeling into your project. Note that this is not a requirement, but since we hadn't introduced modelling at the time of writing your proposal, this is a good time think about how, if at all, you might use modelling in your project.
-   Discuss next steps for your project, identifying concrete tasks that need to be done. Assign at least one task to each member.

```{marginfigure}
When done, close the issue with the relevant commit. You can do this by prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” and then the number of the issue followed by a hashtag (e.g. `Fixes #2`). The issue will be closed when you push the changes to your repo.
```

-   Each member should then open an issue on the repo with their task, and assign it to themselves. Include as much detail as possible to make sure you remember your discussion.
-   **Strongly recommended:** Get a hold of a tutor and run your ideas by them.